version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    # install the requirements for the docs only
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub