name: pyfurnace
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - viennarna
  - pip
  - pip:
    - st-click-detector
    - streamlit_code_editor
    - matplotlib
    - st_forna_component
    - biopython
    - ViennaRNA
    - deap
    - pytest
    - st-oxview
    - numpy
    - git+https://github.com/lorenzo-rovigatti/oxDNA.git#subdirectory=analysi