name: Continuous Integration + Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    name: pytest (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.13"]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Codecov needs >1 commit depth to detect the commit SHA properly
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Show Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install build deps
        run: python -m pip install --upgrade pip wheel

      - name: Install requirements
        run: python -m pip install --upgrade -r requirements-ci.txt

      - name: Install project + test deps
        run: python -m pip install -e . pytest pytest-cov

      - name: Run tests with coverage (XML for Codecov)
        run: |
          pytest tests --cov --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}   # required for v5 unless using OIDC
          env_vars: OS,PYTHON
          flags: ${{ matrix.os }},py${{ matrix.python-version }}
          fail_ci_if_error: true
          verbose: true
